//USERS
GET http://localhost:3000/api/users/

###
GET http://localhost:3000/api/users/1

###
GET http://localhost:3000/api/users/email/alb@mail.com

###
GET http://localhost:3000/api/users/user/albe45

###
POST http://localhost:3000/api/register
Content-Type: application/json

{
    "name": "alvaro",
    "surname": "gonsi",
    "email": "alberjd@mail.com",
    "birth_date": "1996/12/10",
    "gender":"M",
    "user":"srtorti2",
    "password": "12345"
}

###
POST http://localhost:3000/api/login
Content-Type: application/json

{
    "user": "albertokea2",
    "email": "alberto2@mail.com",
    "password": "12345"
}

###
POST http://localhost:3000/api/posts/update
Content-Type: application/json

{
    "genre": "aaa",
    "license": "license",
    "audio": "ccc",
    "key": "G",
    "bpm": 25,
    "extra_tags": "hhh",
    "download": true,
    "description": "sodjaiosd",
    "idpost": "4"
}

###
POST http://localhost:3000/api/posts/new
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjgsImV4cGlyZSI6MTYxNjUxNTE1NCwiaWF0IjoxNjE2NDk3MTU0fQ.yxZwv4y5HxgyOHmlL8iwUY6f8-3QfEGTo_gShY3G8u8

{
    "genre": "aaa",
    "license": "license",
    "audio": "ccc",
    "key": "G",
    "bpm": 25,
    "extra_tags": "hhh",
    "download": true,
    "description": "sodjaiosd",
    "idpost": "4"
}