//USERS
GET http://localhost:3000/api/albertokea2

###
GET http://localhost:3000/api/users/1

###
GET http://localhost:3000/api/users/email/alb@mail.com

###
GET http://localhost:3000/api/users/user/albe45

###
POST http://localhost:3000/api/register
Content-Type: application/json

{
    "name": "alvaro",
    "surname": "gonsi",
    "email": "alberjd@mail.com",
    "birth_date": "1996/12/10",
    "gender":"M",
    "user":"srtorti2",
    "password": "12345"
}

###
POST http://localhost:3000/api/login
Content-Type: application/json

{
    "user": "srtorti2",
    "email": "",
    "password": "12345"
}

###
POST http://localhost:3000/api/posts/update
Content-Type: application/json

{
    "genre": "aaa",
    "license": "license",
    "audio": "ccc",
    "key": "G",
    "bpm": 25,
    "extra_tags": "hhh",
    "download": true,
    "description": "sodjaiosd",
    "idpost": "4"
}

###
PUT http://localhost:3000/api/users/update
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEwLCJleHBpcmUiOjE2MTY1MTkwNzEsImlhdCI6MTYxNjUwMTA3MX0.xRL771V-i5URF_47FmNk7qH1ST3ZB_-p7WB3119qsNE

{
    "twitter":"alskdjslakdjsak",
    "iduser":"10"
}
